# Generated by Django 4.0.3 on 2022-04-11 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSubsections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='Reading_subsections', verbose_name='Image')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reading_subsection', to='reading.readingtheme')),
            ],
        ),
    ]
