# Generated by Django 3.2.3 on 2022-03-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reading_Material',
            new_name='ReadingMaterial',
        ),
    ]
