# Generated by Django 4.0.3 on 2022-04-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingmaterial',
            name='voice',
            field=models.FileField(default=1, upload_to='reading_voices'),
            preserve_default=False,
        ),
    ]
