# Generated by Django 4.0.3 on 2022-04-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_readingmaterial_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingmaterial',
            name='voice',
            field=models.FileField(blank=True, upload_to='reading_voices'),
        ),
    ]
