# Generated by Django 4.0.3 on 2022-04-11 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_readingsubsections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingsubsections',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_subsection', to='reading.readingtheme'),
        ),
        migrations.CreateModel(
            name='ReadingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='reading_material', verbose_name='Image')),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reading_material', to='reading.readingsubsections')),
            ],
        ),
    ]
