# Generated by Django 4.0.3 on 2022-04-11 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_alter_readingsubsections_theme_readingmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingmaterial',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_material', to='reading.readingsubsections'),
        ),
    ]
