# Generated by Django 3.2.3 on 2022-03-20 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarSubsections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='grammar_subsections', verbose_name='Image')),
            ],
        ),
        migrations.AddField(
            model_name='grammarmaterial',
            name='image',
            field=models.ImageField(blank=True, upload_to='grammar_material', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='GrammarTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='grammar_theme', verbose_name='Image')),
                ('subsections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_theme', to='grammar.grammarsubsections')),
            ],
        ),
        migrations.AddField(
            model_name='grammarsubsections',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_subsection', to='grammar.grammarmaterial'),
        ),
    ]
