# Generated by Django 3.2.3 on 2022-03-20 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0002_auto_20220320_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammarsubsections',
            name='material',
        ),
        migrations.RemoveField(
            model_name='grammartheme',
            name='subsections',
        ),
        migrations.AddField(
            model_name='grammarmaterial',
            name='subsection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grammar_material', to='grammar.grammarsubsections'),
        ),
        migrations.AddField(
            model_name='grammarsubsections',
            name='theme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='grammar_subsection', to='grammar.grammartheme'),
            preserve_default=False,
        ),
    ]
