# Generated by Django 3.2.3 on 2022-03-20 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0003_auto_20220320_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarmaterial',
            name='subsection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='grammar_material', to='grammar.grammarsubsections'),
            preserve_default=False,
        ),
    ]
