# Generated by Django 4.0.3 on 2022-04-18 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0004_alter_grammarmaterial_subsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarVoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.FileField(upload_to='grammar_voices')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_voices', to='grammar.grammarmaterial')),
            ],
        ),
    ]
