# Generated by Django 4.0.3 on 2022-04-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0005_grammarvoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarmaterial',
            name='voice',
            field=models.FileField(default=1, upload_to='grammar_voices'),
            preserve_default=False,
        ),
    ]
