# Generated by Django 4.0.3 on 2022-04-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0006_grammarmaterial_voice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrammarVoices',
        ),
    ]
