# Generated by Django 4.0.3 on 2022-05-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0009_grammarmaterial_test_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarmaterial',
            name='test_link',
            field=models.URLField(blank=True, db_index=True),
        ),
    ]
